version: "3.9"

services:
  backend:
    build:
      context: ./crm-backend
    ports:
      - "3100:3000"  # Porta externa alterada de 3000 para 3100
    volumes:
      - ./crm-backend:/app
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  frontend:
    build:
      context: ./crm-frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"  # Porta externa alterada de 80 para 8081
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
